# Generated by Django 2.1 on 2018-09-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, choices=[('Anglo-Saxon, Norse, and Celtic', 'Anglo-Saxon, Norse, and Celtic'), ('Archaeology', 'Archaeology'), ('Architecture', 'Architecture'), ('Asian and Middle Eastern Studies', 'Asian and Middle Eastern Studies'), ('Chemical Engineering', 'Chemical Engineering'), ('Classics', 'Classics'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('English', 'English'), ('Geography', 'Geography'), ('History', 'History'), ('History and Modern Languages', 'History and Modern Languages'), ('History and Politics', 'History and Politics'), ('History of Art', 'History of Art'), ('Human, Social, and Political Sciences', 'Human, Social, and Political Sciences'), ('Land Economy', 'Land Economy'), ('Law', 'Law'), ('Linguistics', 'Linguistics'), ('Management Studies', 'Management Studies'), ('Manufacturing Engineering', 'Manufacturing Engineering'), ('Mathematics', 'Mathematics'), ('Medicine', 'Medicine'), ('Modern and Medieval Languages', 'Modern and Medieval Languages'), ('Music', 'Music'), ('Natural Sciences', 'Natural Sciences'), ('Philosophy', 'Philosophy'), ('Psychological and Behavioural Sciences', 'Psychological and Behavioural Sciences'), ('Theology', 'Theology'), ('Veterinary Medicine', 'Veterinary Medicine')], max_length=255),
        ),
    ]
