# Generated by Django 2.1.1 on 2018-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='placeholders/event.png', upload_to='images/events/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(default='placeholders/host.png', upload_to='images/hosts/pictures/%Y/%m/%d/'),
        ),
    ]
