# Generated by Django 2.1 on 2018-09-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180901_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='placeholders/event.jpeg', upload_to='images/events/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(default='placeholders/host.jpeg', upload_to='images/hosts/pictures/%Y/%m/%d/'),
        ),
    ]
