# Generated by Django 2.0.7 on 2018-07-29 11:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.UserCategory')),
            ],
            options={
                'verbose_name_plural': 'User Categories',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='open_to',
            field=mptt.fields.TreeManyToManyField(default=1, related_name='events', to='core.UserCategory'),
        ),
        migrations.AddField(
            model_name='host',
            name='open_to',
            field=mptt.fields.TreeManyToManyField(default=1, related_name='hosts', to='core.UserCategory'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.UserCategory'),
        ),
    ]
