# Generated by Django 2.0.7 on 2018-07-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180730_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='going_to',
            field=models.ManyToManyField(blank=True, related_name='users_going', to='core.Event'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interested_in',
            field=models.ManyToManyField(blank=True, related_name='users_interested', to='core.Event'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='users_subscribed', to='core.Host'),
        ),
    ]
