# Generated by Django 2.0.7 on 2018-07-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180730_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='host',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
