# Generated by Django 2.0.7 on 2018-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180731_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, upload_to='event_images/%Y/%m/%d'),
        ),
    ]
