# Generated by Django 2.0.7 on 2018-08-06 19:08

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_event_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='event_images//%Y/%m/%d/'),
        ),
    ]
