# Generated by Django 2.0.7 on 2018-08-06 20:21

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180806_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.AddField(
            model_name='host',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/hosts/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='host',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
