# Generated by Django 2.0.7 on 2018-08-13 18:19

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180813_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='thumbnail',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='thumbnails/event-categories/', verbose_name='Image'),
        ),
    ]
