# Generated by Django 2.0.7 on 2018-08-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180813_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='going_to',
        ),
    ]
