# Generated by Django 2.0.7 on 2018-08-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_user_going_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Event Category', 'verbose_name_plural': 'Event Categories'},
        ),
        migrations.AlterModelOptions(
            name='hostcategory',
            options={'verbose_name': 'Host Category', 'verbose_name_plural': 'Host Categories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'User Category', 'verbose_name_plural': 'User Categories'},
        ),
    ]
