# Generated by Django 2.0.7 on 2018-08-19 17:52

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180819_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='open_to',
        ),
        migrations.AddField(
            model_name='event',
            name='open_to',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='events', to='core.UserCategory'),
        ),
        migrations.RemoveField(
            model_name='host',
            name='open_to',
        ),
        migrations.AddField(
            model_name='host',
            name='open_to',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='hosts', to='core.UserCategory'),
        ),
    ]
