# Generated by Django 2.1 on 2018-08-24 18:42

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180819_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='open_to',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.UserCategory'),
        ),
        migrations.AlterField(
            model_name='host',
            name='open_to',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='core.UserCategory'),
        ),
    ]
