# Generated by Django 2.1 on 2018-08-24 19:24

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180824_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/hosts/logos/%Y/%m/%d/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='host',
            name='logo_ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='host',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/hosts/pictures/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
