# Generated by Django 2.1 on 2018-08-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, choices=[('Physics', 'Physics')], max_length=255),
        ),
    ]
