# Generated by Django 2.1 on 2018-09-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_user_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science')], max_length=255),
        ),
    ]
