# Generated by Django 2.1 on 2018-08-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20180831_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/Users/lawrence/Development/bridge-app/backend/media_root/placeholders/event.jpeg', upload_to='images/events/%Y/%m/%d/'),
        ),
    ]
