# Generated by Django 2.1 on 2018-08-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20180831_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='thumbnail_ppoi',
        ),
        migrations.RemoveField(
            model_name='hostcategory',
            name='thumbnail_ppoi',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='thumbnail_ppoi',
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/event_categories/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(default='/Users/lawrence/Development/bridge-app/backend/media_root/placeholders/host.jpeg', upload_to='images/hosts/pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='hostcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/host_categories/%Y/%m/%d/'),
        ),
    ]
