# Generated by Django 2.1 on 2018-09-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20180831_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/Users/Matteo/Library/Developer/Bridge/bridge-app/backend/media_root/placeholders/event.jpeg', upload_to='images/events/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(default='/Users/Matteo/Library/Developer/Bridge/bridge-app/backend/media_root/placeholders/host.jpeg', upload_to='images/hosts/pictures/%Y/%m/%d/'),
        ),
    ]
